#! /bin/sh

curl -XPUT "localhost:9200/_river/slide_note/_meta" -d '
{
  "type": "mongodb",
  "mongodb": {
    "db": "slide_note",
    "collection": "slides",
    "servers": [
      { "host": "127.0.0.1", "port": 27017 }
    ],
    "options": { "secondary_read_preference": true }
  },
  "index": {
    "name": "slidesidx",
    "type": "slide"
  }
}'
